# Generated by Django 6.0 on 2025-12-16 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fatura_itemfatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('SALARIO', 'Salário'), ('SERVICO', 'Serviço'), ('OUTRO', 'Outro')], default='FORNECEDOR', max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data'],
            },
        ),
    ]
