# Generated by Django 6.0 on 2025-12-16 15:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_despesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='core.despesa')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='core.fatura')),
            ],
            options={
                'verbose_name': 'Lançamento Diário',
                'verbose_name_plural': 'Lançamentos Diário',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoRazao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.conta')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='core.lancamentodiario')),
            ],
            options={
                'verbose_name': 'Movimento Razão',
                'verbose_name_plural': 'Movimentos Razão',
            },
        ),
    ]
