# Generated by Django 6.0 on 2025-12-19 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Documento')),
                ('data_vencimento', models.DateField()),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('REGISTADA', 'Registada'), ('PAGA', 'Paga'), ('ANULADA', 'Anulada')], default='RASCUNHO', max_length=20)),
                ('referencia_fornecedor', models.CharField(blank=True, help_text='Ex: Nº da fatura do fornecedor', max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_imposto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.fornecedor')),
            ],
        ),
        migrations.AddField(
            model_name='lancamentodiario',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='core.compra'),
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_imposto', models.DecimalField(decimal_places=2, default=14.0, help_text='Ex: 14 para 14%', max_digits=5)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.compra')),
            ],
        ),
    ]
