# Generated by Django 6.0 on 2025-12-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_compra_lancamentodiario_compra_itemcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentodiario',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ABERTURA', 'Abertura de Exercício'), ('FECHO', 'Fecho de Exercício')], default='NORMAL', max_length=20),
        ),
    ]
