# Generated by Django 6.0 on 2025-12-26 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_fatura_estado_pagamentofatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('REGISTADA', 'Registada'), ('PAGAMENTO_PARCIAL', 'Pagamento Parcial'), ('PAGA', 'Paga'), ('ANULADA', 'Anulada')], default='RASCUNHO', max_length=20),
        ),
        migrations.CreateModel(
            name='PagamentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pagamento', models.CharField(choices=[('CAIXA', 'Caixa'), ('BANCO', 'Banco')], default='BANCO', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.compra')),
            ],
            options={
                'verbose_name': 'Pagamento de Compra',
                'verbose_name_plural': 'Pagamentos de Compras',
            },
        ),
    ]
