# Generated by Django 6.0 on 2025-12-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_compra_estado_pagamentocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='compra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras_reg', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='conta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesas_reg', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='lancamentodiario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_reg', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_contabilistico',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='conta',
            name='codigo',
            field=models.CharField(help_text='Código da conta. Ex: 31, 31.1', max_length=20),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='numero',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='numero',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='codigo_contabilistico',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='lancamentodiario',
            name='numero',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('numero', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='conta',
            unique_together={('codigo', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='despesa',
            unique_together={('numero', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='fatura',
            unique_together={('numero', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='lancamentodiario',
            unique_together={('numero', 'empresa')},
        ),
    ]
