# Generated by Django 6.0 on 2025-12-26 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cliente_empresa_compra_empresa_conta_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compras_reg', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='despesas_reg', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='lancamentodiario',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_reg', to='core.empresa'),
        ),
    ]
