# Generated by Django 6.0 on 2025-12-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cliente_empresa_alter_compra_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('RAZAO', 'Razão'), ('INTEGRACAO', 'Integração'), ('MOVIMENTO', 'Movimento')], default='MOVIMENTO', max_length=20),
        ),
    ]
