# Generated by Django 6.0 on 2025-12-26 19:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_conta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='moeda_estrangeira',
            field=models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], default='USD', max_length=3, verbose_name='Moeda de Referência'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='moeda_padrao',
            field=models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], default='AOA', max_length=3, verbose_name='Moeda Base'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='taxa_cambio',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12, verbose_name='Taxa de Câmbio (Base/Ref)'),
        ),
    ]
