# Generated by Django 6.0 on 2025-12-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_empresa_moeda_estrangeira_empresa_moeda_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plano_modelo',
            field=models.CharField(choices=[('PGC_GERAL', 'PGC Angola - Plano Geral'), ('PGC_SIMP', 'PGC Angola - Regime Simplificado'), ('PERSONALIZADO', 'Personalizado (Importação Manual)')], default='PGC_GERAL', max_length=30, verbose_name='Modelo de Plano de Contas'),
        ),
    ]
