# Generated by Django 6.0 on 2025-12-26 19:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_empresa_plano_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='taxa_cambio',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Taxa de Câmbio (Base/Ref)'),
        ),
    ]
