# Generated by Django 6.0 on 2025-12-26 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_empresa_options_cambio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cambio',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Câmbio', 'verbose_name_plural': 'Câmbios'},
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('numero_seguranca_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Segurança Social')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo/Função')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salário Base')),
                ('subsidio_alimentacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subsídio de Alimentação')),
                ('subsidio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subsídio de Transporte')),
                ('outros_abonos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Outros Abonos (Sujeitos a SS)')),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='ProcessamentoSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data_processamento', models.DateField(default=django.utils.timezone.now)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subsidio_alimentacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subsidio_transporte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outros_abonos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inss_funcionario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inss_empresa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('irt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_descontos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salario_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processamentos', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
    ]
