# Generated by Django 6.0 on 2025-12-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cambio_options_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamentosalarial',
            name='contabilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processamentosalarial',
            name='desconto_faltas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='processamentosalarial',
            name='dias_falta',
            field=models.IntegerField(default=0, verbose_name='Faltas (Dias)'),
        ),
        migrations.AddField(
            model_name='processamentosalarial',
            name='horas_100',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas Extras (100%)'),
        ),
        migrations.AddField(
            model_name='processamentosalarial',
            name='horas_50',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas Extras (50%)'),
        ),
        migrations.AddField(
            model_name='processamentosalarial',
            name='lancamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salarios', to='core.lancamentodiario'),
        ),
        migrations.AddField(
            model_name='processamentosalarial',
            name='valor_horas_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
