# Generated by Django 6.0 on 2025-12-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_processamentosalarial_contabilizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processamentosalarial',
            name='dias_falta',
        ),
        migrations.AddField(
            model_name='processamentosalarial',
            name='horas_falta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Faltas (Horas)'),
        ),
    ]
