# Generated by Django 6.0 on 2025-12-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_processamentosalarial_dias_falta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='aplicar_retencao',
            field=models.BooleanField(default=False, verbose_name='Aplicar Retenção na Fonte (6.5%)'),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_retencao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total_imposto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
