# Generated by Django 6.0 on 2025-12-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_compra_aplicar_retencao_compra_valor_retencao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='retencao_paga',
            field=models.BooleanField(default=False, verbose_name='Retenção Liquidada/DAR Recebido'),
        ),
    ]
