# Generated by Django 6.0 on 2025-12-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_compra_retencao_paga'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='aplicar_retencao',
            field=models.BooleanField(default=False, verbose_name='Aplicar Retenção 6.5%'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='retencao_paga',
            field=models.BooleanField(default=False, verbose_name='DAR Recebido'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_retencao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Retido'),
        ),
    ]
