# Generated by Django 6.0 on 2025-12-26 23:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fatura_aplicar_retencao_fatura_retencao_paga_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentorazao',
            options={},
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('estado', models.CharField(choices=[('EM_CURSO', 'Em Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EM_CURSO', max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-data', '-created_at'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código/Referência')),
                ('nome', models.CharField(max_length=200, verbose_name='Designação')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('MERCADORIA', 'Mercadoria'), ('MATERIA_PRIMA', 'Matéria-Prima'), ('PRODUTO_ACABADO', 'Produto Acabado'), ('SERVICO', 'Serviço')], default='MERCADORIA', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('unidade', models.CharField(default='UN', help_text='Ex: UN, KG, L, M, CX', max_length=20)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Preço de Venda')),
                ('stock_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Stock Atual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Stock Máximo')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta_stock', models.ForeignKey(blank=True, help_text='Conta PGC para valorização do stock (ex: 33)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_stock', to='core.conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimentoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('INVENTARIO', 'Inventário')], max_length=20)),
                ('origem', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('PRODUCAO', 'Produção'), ('DEVOLUCAO', 'Devolução'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('INVENTARIO', 'Inventário')], max_length=20)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_stock', to='core.compra')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_stock', to='core.empresa')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_stock', to='core.fatura')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='core.inventario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.produto')),
            ],
            options={
                'verbose_name': 'Movimento de Stock',
                'verbose_name_plural': 'Movimentos de Stock',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinhaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock no Sistema')),
                ('stock_contado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Stock Contado')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço de Custo')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='core.inventario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_inventario', to='core.produto')),
            ],
            options={
                'verbose_name': 'Movimento Razão',
                'verbose_name_plural': 'Movimentos Razão',
            },
        ),
    ]
