# Generated by Django 6.0 on 2026-01-05 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_movimentorazao_options_inventario_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaIRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Limite do Escalão')),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa (%)')),
                ('parcela_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Parcela Fixa')),
                ('excesso', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Parcela a Abater/Excesso')),
            ],
            options={
                'verbose_name': 'Tabela IRT',
                'verbose_name_plural': 'Tabela IRT',
                'ordering': ['limite'],
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='conta_stock',
            field=models.ForeignKey(blank=True, help_text='Conta PGC para valorização do stock (Classe 2: 22-Matérias-Primas, 26-Mercadorias)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_stock', to='core.conta'),
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horas', models.DecimalField(decimal_places=2, help_text='Número de horas de ausência', max_digits=4)),
                ('justificada', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('comprovativo', models.FileField(blank=True, null=True, upload_to='rh/faltas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tipo', models.CharField(choices=[('50', '50% (Dia Útil/Diurno)'), ('100', '100% (Noturno/Fim de Semana/Feriado)')], default='50', max_length=3)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('aprovado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extras', to='core.funcionario')),
            ],
        ),
    ]
