# Generated by Django 6.0 on 2026-01-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_tabelairt_alter_produto_conta_stock_falta_horaextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelairt',
            name='excesso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Parcela a Abater/Excesso'),
        ),
        migrations.AlterField(
            model_name='tabelairt',
            name='limite',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Limite do Escalão'),
        ),
        migrations.AlterField(
            model_name='tabelairt',
            name='parcela_fixa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Parcela Fixa'),
        ),
    ]
