# Generated by Django 6.0 on 2026-01-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_tabelairt_excesso_alter_tabelairt_limite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: IVA_NORMAL, IND_NORMAL', max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('taxa', models.DecimalField(decimal_places=2, help_text='Percentagem do imposto', max_digits=5)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taxa de Imposto',
                'verbose_name_plural': 'Taxas de Imposto',
            },
        ),
    ]
