# Generated by Django 6.0 on 2026-01-05 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_taxaimposto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='taxa_retencao',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.5'), max_digits=5, verbose_name='Taxa de Retenção (%)'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='taxa_retencao',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.5'), max_digits=5, verbose_name='Taxa de Retenção (%)'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='aplicar_retencao',
            field=models.BooleanField(default=False, verbose_name='Aplicar Retenção'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_retencao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Retido'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='aplicar_retencao',
            field=models.BooleanField(default=False, verbose_name='Aplicar Retenção'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_retencao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Retido'),
        ),
    ]
