# Generated by Django 6.0 on 2026-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_compra_taxa_retencao_fatura_taxa_retencao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(choices=[('AO', 'Angola'), ('PT', 'Portugal'), ('BR', 'Brasil'), ('US', 'Estados Unidos')], default='AO', max_length=2, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='moeda_estrangeira',
            field=models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)'), ('BRL', 'Real (BRL)')], default='USD', max_length=3, verbose_name='Moeda de Referência'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='moeda_padrao',
            field=models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)'), ('BRL', 'Real (BRL)')], default='AOA', max_length=3, verbose_name='Moeda Base'),
        ),
    ]
