# Generated by Django 6.0 on 2026-01-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_empresa_pais_alter_empresa_moeda_estrangeira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='tipo_entidade',
            field=models.CharField(choices=[('NENHUM', 'Nenhum'), ('CLIENTE', 'Cliente'), ('FORNECEDOR', 'Fornecedor'), ('ESTADO', 'Estado'), ('BANCO', 'Banco'), ('CAIXA', 'Caixa')], default='NENHUM', max_length=20, verbose_name='Tipo de Terceiro/Entidade'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='moeda_estrangeira',
            field=models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], default='USD', max_length=3, verbose_name='Moeda de Referência'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='moeda_padrao',
            field=models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], default='AOA', max_length=3, verbose_name='Moeda Base'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(choices=[('AO', 'Angola'), ('PT', 'Portugal'), ('FR', 'França'), ('ES', 'Espanha'), ('US', 'Estados Unidos')], default='AO', max_length=2, verbose_name='País'),
        ),
    ]
