# Generated by Django 6.0 on 2026-01-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_conta_tipo_entidade_alter_empresa_moeda_estrangeira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('RAZAO', 'Razão'), ('INTEGRACAO', 'Integração'), ('MOVIMENTO', 'Movimento'), ('APURAMENTO', 'Apuramento'), ('A', 'Apuramento')], default='MOVIMENTO', max_length=20),
        ),
    ]
