from django.urls import path
from django.contrib.auth import views as auth_views
from . import views, views_relatorios, views_rh, views_relatorios_extra, views_cambios, views_stock, views_impostos

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('', views.home, name='home'),
    path('atualizar-cambios/', views_cambios.atualizar_cambios, name='atualizar_cambios'),
    # ...
    # Impostos
    path('contabilidade/taxas/', views_impostos.taxas_imposto_list, name='taxas_imposto_list'),
    path('contabilidade/taxas/atualizar/', views_impostos.atualizar_taxas_padrao, name='atualizar_taxas_padrao'),
    path('contabilidade/taxas/excel/', views_impostos.exportar_taxas_excel, name='exportar_taxas_excel'),
    
    path('clientes/', views.clientes_list, name='clientes'),
    path('clientes/editar/<int:pk>/', views.editar_cliente, name='editar_cliente'),
    path('clientes/excluir/<int:pk>/', views.excluir_cliente, name='excluir_cliente'),
    path('clientes/exportar/excel/', views.exportar_clientes_excel, name='exportar_clientes_excel'),
    path('clientes/exportar/pdf/', views.exportar_clientes_pdf, name='exportar_clientes_pdf'),
    path('fornecedores/', views.fornecedores_list, name='fornecedores'),
    path('fornecedores/editar/<int:pk>/', views.editar_fornecedor, name='editar_fornecedor'),
    path('fornecedores/excluir/<int:pk>/', views.excluir_fornecedor, name='excluir_fornecedor'),
    path('fornecedores/exportar/excel/', views.exportar_fornecedores_excel, name='exportar_fornecedores_excel'),
    path('fornecedores/exportar/pdf/', views.exportar_fornecedores_pdf, name='exportar_fornecedores_pdf'),
    
    path('contas-correntes/', views.contas_correntes_list, name='contas_correntes_list'),
    path('contas-correntes/<str:tipo>/<int:pk>/', views.conta_corrente_detalhe, name='conta_corrente_detalhe'),
    path('contas-correntes/<int:pk>/exportar/excel/', views.exportar_conta_corrente_excel, name='exportar_conta_corrente_excel'),
    path('contas-correntes/<int:pk>/exportar/pdf/', views.exportar_conta_corrente_pdf, name='exportar_conta_corrente_pdf'),
    path('faturas/', views.faturas_list, name='faturas_list'),
    path('faturas/nova/', views.nova_fatura, name='nova_fatura'),
    path('faturas/<int:pk>/', views.fatura_detalhe, name='fatura_detalhe'),
    path('faturas/<int:pk>/pagar/', views.registrar_pagamento_fatura, name='registrar_pagamento_fatura'),
    path('faturas/<int:pk>/estado/<str:estado>/', views.mudar_estado_fatura, name='mudar_estado_fatura'),
    path('faturas/<int:fatura_id>/pdf/', views.pdf_fatura, name='pdf_fatura'),
    path('compras/', views.compras_list, name='compras_list'),
    path('compras/nova/', views.nova_compra, name='nova_compra'),
    path('compras/<int:pk>/', views.compra_detalhe, name='compra_detalhe'),
    path('compras/<int:pk>/pagar/', views.registrar_pagamento_compra, name='registrar_pagamento_compra'),
    path('compras/<int:pk>/estado/<str:estado>/', views.mudar_estado_compra, name='mudar_estado_compra'),
    path('despesas/', views.despesas_list, name='despesas'),
    path('configuracao/', views.configuracao_empresa, name='configuracao_empresa'),
    path('configuracao/editar/<int:pk>/', views.editar_empresa, name='editar_empresa'),
    path('configuracao/selecionar/<int:pk>/', views.selecionar_empresa, name='selecionar_empresa'),
    path('configuracao/limpar-dados/', views.limpar_dados_empresa, name='limpar_dados_empresa'),
    path('configuracao/cambios/', views.lista_cambios, name='lista_cambios'),
    path('configuracao/cambios/eliminar/<int:pk>/', views.eliminar_cambio, name='eliminar_cambio'),
    
    # Usuários (Administração)
    path('configuracao/usuarios/', views.usuarios_list, name='usuarios_list'),
    path('configuracao/usuarios/novo/', views.novo_usuario, name='novo_usuario'),
    path('configuracao/usuarios/editar/<int:pk>/', views.editar_usuario, name='editar_usuario'),
    path('configuracao/usuarios/excluir/<int:pk>/', views.excluir_usuario, name='excluir_usuario'),
    path('configuracao/abertura/', views.lancamento_abertura, name='lancamento_abertura'),
    path('plano-contas/', views.plano_contas, name='plano_contas'),
    path('plano-contas/nova/', views.nova_conta, name='nova_conta'),
    path('plano-contas/editar/<int:pk>/', views.editar_conta, name='editar_conta'),
    path('plano-contas/eliminar/<int:pk>/', views.eliminar_conta, name='eliminar_conta'),
    path('plano-contas/pdf/', views.pdf_plano_contas, name='pdf_plano_contas'),
    path('plano-contas/importar/', views.importar_plano_contas, name='importar_plano_contas'),
    path('plano-contas/exportar/', views.exportar_plano_contas_excel, name='exportar_plano_contas_excel'),
    path('plano-contas/inicializar/', views.inicializar_plano, name='inicializar_plano'),
    path('diario/lancamentos/', views.lancamentos_list, name='lancamentos_list'),
    path('diario/novo/', views.novo_lancamento, name='novo_lancamento'),
    path('diario/<int:pk>/', views.lancamento_detalhe, name='lancamento_detalhe'),
    
    # Relatórios
    path('relatorios/', views_relatorios.relatorios_menu, name='relatorios_menu'),
    path('relatorios/balancete/', views_relatorios.relatorio_balancete, name='relatorio_balancete'),
    path('relatorios/razao/', views_relatorios.relatorio_razao, name='relatorio_razao'),
    path('relatorios/diario/', views_relatorios.relatorio_diario, name='relatorio_diario'),
    path('relatorios/demonstracao-resultados/', views_relatorios.relatorio_demonstracao_resultados, name='relatorio_demonstracao_resultados'),
    path('relatorios/balanco-patrimonial/', views_relatorios.relatorio_balanco_patrimonial, name='relatorio_balanco_patrimonial'),
    path('relatorios/mapa-iva/', views_relatorios.relatorio_mapa_iva, name='relatorio_mapa_iva'),
    path('relatorios/fluxo-caixa/', views_relatorios.relatorio_fluxo_caixa, name='relatorio_fluxo_caixa'),
    path('relatorios/balancete-resultados/', views_relatorios.relatorio_balancete_resultados, name='relatorio_balancete_resultados'),
    path('relatorios/apuramento/', views_relatorios.apuramento_resultados, name='apuramento_resultados'),
    path('relatorios/saft/', views_relatorios.exportar_saft_xml, name='exportar_saft_xml'),
    path('relatorios/retencoes/', views_relatorios_extra.relatorio_retencoes, name='relatorio_retencoes'),
    path('relatorios/retencoes/liquidar/<int:pk>/', views_relatorios_extra.liquidar_retencao_compra, name='liquidar_retencao_compra'),
    path('relatorios/retencoes/confirmar-dar/<int:pk>/', views_relatorios_extra.confirmar_dar_venda, name='confirmar_dar_venda'),
    
    # Recursos Humanos
    path('rh/funcionarios/', views_rh.funcionarios_list, name='funcionarios_list'),
    path('rh/funcionarios/editar/<int:pk>/', views_rh.editar_funcionario, name='editar_funcionario'),
    path('rh/processamento/', views_rh.processamento_rh, name='processamento_rh'),
    path('rh/processamento/editar/<int:pk>/', views_rh.editar_processamento, name='editar_processamento'),
    path('rh/processamento/contabilizar/', views_rh.contabilizar_salarios, name='contabilizar_salarios'),
    path('rh/recibo/<int:pk>/', views_rh.pdf_recibo_salario, name='pdf_recibo_salario'),
    path('rh/folha/', views_rh.pdf_folha_remuneracoes, name='pdf_folha_remuneracoes'),
    path('rh/irt/', views_rh.tabela_irt_list, name='tabela_irt'),
    path('rh/irt/atualizar/', views_rh.atualizar_tabela_irt, name='atualizar_tabela_irt'),
    path('rh/lancamentos/', views_rh.lancamentos_rh_list, name='lancamentos_rh_list'),
    path('rh/lancamentos/falta/nova/', views_rh.nova_falta, name='nova_falta'),
    path('rh/lancamentos/hora-extra/nova/', views_rh.nova_hora_extra, name='nova_hora_extra'),
    
    # Gestão de Stocks
    path('stock/produtos/', views_stock.produtos_list, name='produtos_list'),
    path('stock/produtos/<int:pk>/', views_stock.produto_detalhe, name='produto_detalhe'),
    path('stock/produtos/editar/<int:pk>/', views_stock.editar_produto, name='editar_produto'),
    path('stock/movimentos/', views_stock.movimentos_stock_list, name='movimentos_stock_list'),
    path('stock/inventarios/', views_stock.inventarios_list, name='inventarios_list'),
    path('stock/inventarios/<int:pk>/', views_stock.inventario_detalhe, name='inventario_detalhe'),
    path('stock/inventarios/<int:inventario_pk>/linha/<int:linha_pk>/atualizar/', views_stock.atualizar_contagem, name='atualizar_contagem'),
    path('stock/inventarios/<int:pk>/finalizar/', views_stock.finalizar_inventario, name='finalizar_inventario'),
]
